export const SECRET_KEY = {
  ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_SECRET: 'JWT_SECRET',
  GITHUB_CLIENT_ID: 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET: 'GITHUB_CLIENT_SECRET',
  GITHUB_CALLBACK_URL: 'GITHUB_CALLBACK_URL',
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
} as const;
